FROM alpine:latest

# Add the commands needed to put your compiled go binary in the container and
# run it when the container starts.
#
# See https://docs.docker.com/engine/reference/builder/ for a reference of all
# the commands you can use in this file.
#
# In order to use this file together with the docker-compose.yml file in the
# same directory, you need to ensure the image you build gets the name
# "kadlab", which you do by using the following command:
#
# $ docker build . -t kadlab

#WORKDIR /app 
#RUN mkdir /app 
#ADD . /app/
#COPY 
#RUN docker build . -t kadlab
#USER root
#CMD ["./kadlab"]

#RUN mkdir /app 
#ADD . /app/
#WORKDIR /app 


#RUN docker build . -t kadlab
#USER root
#EXPOSE 8080
#CMD ["kadlab"]
#ENTRYPOINT ["kadlab"]